name: Build
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      matrix_os:
        type: string
        default: '["windows-latest", "ubuntu-latest", "macos-latest"]'
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: ${{ fromJSON(inputs.matrix_os) }}
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Rust toolchains
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: wasm32-unknown-unknown
          components: clippy,rustfmt
      - name: Build lib
        run: cargo build -p goodomain --release -vv
      - name: Build CLI
        run: cargo build -p goodomain-cli --release -vv
      - name: Build WASM binding
        run: cargo build -p goodomain-wasm --target wasm32-unknown-unknown --release -vv
