name: WebApp
on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: "0 23 * * *" # CST 7:00 = UTC prev day 23:00
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  build-lib:
    uses: ./.github/workflows/build.yml
  build-webapp:
    needs: [build-lib]
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Rust toolchains
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: wasm32-unknown-unknown
      - name: Install node toolchains
        uses: actions/setup-node@v4
        with:
          version: lts
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: false
      - name: Install wasm-pack
        run: |
          pnpm install -g wasm-pack
      - name: Build goodomain-wasm nodejs package
        run: |
          wasm-pack build bindings/goodomain-wasm --release
          mv bindings/goodomain-wasm/pkg web
      - name: Build web app
        working-directory: web/app
        run: |
          pnpm install
          pnpm run build
        env:
          BASE_PATH: /goodomain
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: web/app/build
  deploy:
    needs: [build-webapp]
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
